[[VALIDATORS]]
public_key = "nHU74qX4tCQDSpE6zBS5PB3jybuGZJ7QMbeyLWDQRy3Lhb4DYDSR"
attestation = "BA3E03128F03B64F0E07B1067BA2E23CCF3347B40D6E28CB305984A2F2C42A3819D8419BCCF06DDE17566338F70B3DF8908096D73F71CF392E9E7C3BAB08FE02"
network = "testnet"
